### ISSUE TITLE
Form is always showing up on Dataset Page

### ISSUE THREAD

**Issue by amaliebarras** [open-austin/data-portal#19]
- [x] remove button-y metadata
- [x] remove voting functionality
- [x] redesign based on removing project page
- [x] figure out why file type labels are buggy
- [x] why is edit form always showing up?

**Comment by amaliebarras** [comment]
hey @sya - any word on this problem with the edit form? do you need help from anyone? we could ask at hack night tomorrow during intros

**Comment by avickers** [comment]
[See this](https://github.com/timwis/jkan/blob/gh-pages/scripts/src/components/view-switcher.js).

`[data-component~=view-switcher] [data-hook~=view] {
  display: none; }` is in our files, but you switched to using SASS.  Does SASS know how to deal with data-components?  Try switching it back to normal CSS and see if the view switcher starts working again.

edit: After more research, the select all attribute/value selector should be fine in SASS 3.4+.  The form should only be showing when the query string "?view=edit" is present.  Tomorrow we can check to see whether the query string is always present or if it's showing even without the query string.

**Comment by avickers** [comment]
I found the issue with this and likely the other button bug as well.  I will either share the solution at hack night tonight or submit a pull request and then close.

**Comment by amaliebarras** [comment]
Thanks @avickers !!!
